#!/usr/bin/env sh

low_threshold=40
low_color=#FFAE00

state_chr=CHR
state_dis=DIS

while getopts t:u:c:d: opt; do
  case "$opt" in
    t) low_threshold="$OPTARG" ;;
    u) low_color="$OPTARG" ;;
    c) state_chr="$OPTARG" ;;
    d) state_dis="$OPTARG" ;;
  esac
done


percentage=$(acpi -b | awk -F'[ ,]+' '{ print $4 }' | sed 's/.$//')
state=$(acpi -b | awk -F'[ ,]+' '{ print $3 }')

case "$state" in
  Charging)
    state_name="$state_chr"
    ;;
  Discharging)
    state_name="$state_dis"
    ;;
esac


printf "%s%% %s\n" "$percentage" "$state_name"
printf "%s%%\n" "$percentage"

if [ "$state" = Discharging ] && [ "$percentage" -lt "$low_threshold" ]; then
  printf "%s\n" "$low_color"
fi
