#!/usr/bin/env sh

if [ -n "$BLOCK_INSTANCE" ]; then
  device_name="$BLOCK_INSTANCE"
else
  device_name='battery_BAT0'
fi

low_threshold=40
low_color=#FFAE00

state_chr=CHR
state_dis=DIS
state_full=FULL

while getopts n:t:u:c:d:f: opt; do
    case "$opt" in
        n) device_name="$OPTARG" ;;
        t) low_threshold="$OPTARG" ;;
        u) low_color="$OPTARG" ;;
        c) state_chr="$OPTARG" ;;
        d) state_dis="$OPTARG" ;;
        f) state_full="$OPTARG" ;;
    esac
done


device="/org/freedesktop/UPower/devices/$device_name"
percentage=$(upower -i "$device" | grep percentage | awk '{print $2}' | sed 's/.$//')
state=$(upower -i "$device" | grep state | awk '{print $2}')

if [ -z "$percentage" ]; then
  echo >&2 "battery_upower: percentage value for $device not found, aborting"
  exit 1
fi

case "$state" in
  charging|pending-charge)
    state_name="$state_chr"
    ;;
  discharging|pending-discharge|empty)
    state_name="$state_dis"
    ;;
  fully-charged)
    state_name="$state_full"
    ;;
esac


printf "%s%% %s\n" "$percentage" "$state_name"
printf "%s%%\n" "$percentage"

if [ "$state" = discharging ] && [ "$percentage" -lt "$low_threshold" ]; then
  echo "$low_color"
fi
