#!/usr/bin/env sh

hide_inactive=0

while getopts q opt; do
  case "$opt" in
    q) hide_inactive=1 ;;
  esac
done

pgrep -fx '/bin/sh /usr/games/steam.*' > /dev/null
if [ $? -eq 0 ]; then
  status=On
else
  status=Off

  if [ $hide_inactive -eq 1 ]; then
    exit 0
  fi
fi

printf "%s\n" "$status"
printf "%s\n" "$status"
