#!/usr/bin/env sh

vpn=$(for fn in /var/run/openvpn/*.pid ; do
  service=$(basename "$fn" .pid)
  status=$(service openvpn status "$service")

  case "$status" in
    *' is running' ) printf "%s," "$service"
  esac
done | sort | sed 's/,$/\n/')

printf "%s\n" "$vpn"
printf "\n"
