#!/usr/bin/env sh

hide_inactive=0

if [ -n "$BLOCK_INSTANCE" ]; then
  username="$BLOCK_INSTANCE"
fi

while getopts o:u:q opt; do
  case "$opt" in
    u) username="$OPTARG" ;;
    q) hide_inactive=1 ;;
  esac
done


if [ -n "$username" ]; then
  db=$(find "$HOME/.Skype/$username/" -name main.db -print -quit)
else
  db=$(find "$HOME/.Skype/" -name main.db -print -quit)
fi

pgrep -fx skype > /dev/null
if [ $? -eq 0 ]; then
  status=On
else
  status=Off

  if [ $hide_inactive -eq 1 ]; then
    exit 0
  fi
fi

unread=$(sqlite3 "$db" "select count(*) from Messages where consumption_status != 0;")


printf "%s [%s]\n" "$status" "$unread"
printf "[%s]\n" "$unread"

